Bump elasticsearch version to 7.9.1 and release version to 1.10.1.0
opendistro-for-elasticsearch/security pull request #706
Opened 2020-09-08 19:05 UTC by camerski

*Description of changes:*
Update OpenDistro version to 1.10.1.0 and elasticsearch dependency to 7.9.1.

*Testing:*
Ran `OPENDISTRO_SECURITY_TEST_OPENSSL_OPT=true mvn -B test` (same as what the ci workflow does).

Test results: `Tests run: 926, Failures: 0, Errors: 0, Skipped: 28`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-08 19:45 UTC, vrozov requested changes
Please split into 2 commits. See https://github.com/opendistro-for-elasticsearch/security/pull/661 and https://github.com/opendistro-for-elasticsearch/security/pull/671

2020-09-08 20:00 UTC, camerski commented
> Please split into 2 commits. See #661 and #671

Sure, no problem. I'll update this one to be just the elasticsearch bump and create a new PR for the plugin version change.

2020-09-09 00:50 UTC, hardik-k-shah approved these changes

2020-09-09 19:08 UTC, vrozov approved these changes

2020-09-09 19:08 UTC, merged