Only reload cTypes that ConfigUpdateRequest requires
opendistro-for-elasticsearch/security pull request #942
Opened 2020-12-29 01:10 UTC by cliu123

##  opendistro-for-elasticsearch/security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 
 
 
 2. __Github Issue # or road-map entry, if available:__

 3. __Description of changes:__

 4. __Why these changes are required?__ 

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from master branch?__ (_If yes, please add backport PR # and commits #_)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-29 19:09 UTC, vrozov requested changes
-1: `nodeOperation()` already reloads `CType` included into the `ConfigUpdateRequest`.

2020-12-29 19:09 UTC, vrozov commented on src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/TransportConfigUpdateAction.java
> +            if (!Arrays.asList(allCTypes).contains(ct))
Under what condition `allCTypes` does not contain `ct`?

2021-01-05 20:13 UTC, vrozov requested changes
The solution should cover not only security config but all other CTypes as well.

2021-01-05 20:33 UTC, cliu123 commented
> The solution should cover not only security config but all other CTypes as well.

I understand that. The follow-up changes will be made before the PR gets published for review.

2021-01-11 19:38 UTC, closed without merging